#!/usr/bin/env php
<?php
/**
 * Renders the UI performance benchmark JSON as the per-run job summary table,
 * grouped by scenario category. The PR comment is generated by
 * write-perf-comment.php; this script only renders the full single-run table.
 *
 * @package Cortext
 */

declare(strict_types=1);

require_once __DIR__ . '/perf-ui-scenario-labels.php';

$args         = parse_args( $argv );
$current_path = $args['current'] ?? 'artifacts/perf-ui.json';
$summary_path = $args['summary'] ?? getenv( 'GITHUB_STEP_SUMMARY' );

$output = build_output( $current_path );
// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- CLI markdown output for GitHub summaries stays unescaped.
echo $output;

if ( is_string( $summary_path ) && '' !== $summary_path ) {
	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_file_put_contents -- Standalone CI helper writes to GitHub's summary file.
	file_put_contents( $summary_path, $output, FILE_APPEND );
}

/**
 * @param array<int,string> $argv
 * @return array<string,string>
 */
function parse_args( array $argv ): array {
	$args = array();
	foreach ( array_slice( $argv, 1 ) as $arg ) {
		if ( ! str_starts_with( $arg, '--' ) ) {
			continue;
		}
		$parts = explode( '=', substr( $arg, 2 ), 2 );
		$key   = $parts[0] ?? '';
		if ( '' === $key ) {
			continue;
		}
		$args[ $key ] = $parts[1] ?? '1';
	}
	return $args;
}

function build_output( string $current_path ): string {
	$current = load_report( $current_path );
	if ( null === $current ) {
		return "UI performance run produced no output.\n";
	}

	$scenarios = is_array( $current['scenarios'] ?? null ) ? $current['scenarios'] : array();
	if ( count( $scenarios ) === 0 ) {
		return "UI performance run had no scenarios.\n";
	}

	$labels = perf_ui_scenario_labels();

	// Categories are ordered broadest first; the id is the tag the spec
	// emits and the label is the section header in the table.
	$category_order = array(
		'collection_read' => 'Collection',
		'row'             => 'Row',
		'column'          => 'Column',
		'navigation'      => 'Navigation',
		'surface'         => 'Surface',
	);

	$grouped = array_fill_keys( array_keys( $category_order ), array() );
	$unknown = array();
	foreach ( $scenarios as $name => $data ) {
		if ( ! is_array( $data ) ) {
			continue;
		}
		$category = (string) ( $data['category'] ?? '' );
		if ( isset( $grouped[ $category ] ) ) {
			$grouped[ $category ][ $name ] = $data;
		} else {
			$unknown[ $name ] = $data;
		}
	}
	if ( count( $unknown ) > 0 ) {
		$grouped['_uncategorized']        = $unknown;
		$category_order['_uncategorized'] = 'Uncategorized';
	}

	$headers    = array( 'Scenario', 'ready ms', 'rows API ms', 'REST', 'longtask total' );
	$alignments = array( 'left', 'right', 'right', 'right', 'right' );
	$rows       = array();

	foreach ( $category_order as $category_id => $category_label ) {
		if ( empty( $grouped[ $category_id ] ) ) {
			continue;
		}
		$rows[] = array( '**' . $category_label . '**', '', '', '', '' );
		foreach ( $grouped[ $category_id ] as $name => $data ) {
			$rows[] = array(
				$labels[ $name ] ?? $name,
				ui_metric_value( $data['ready_ms'] ?? null ),
				ui_metric_value( $data['rows_api_ms'] ?? null ),
				ui_metric_value( $data['rest_request_count'] ?? null ),
				ui_metric_value( $data['long_task_total_ms'] ?? null ),
			);
		}
	}

	$lines = array( '## UI performance', '' );
	$lines = array_merge( $lines, markdown_table( $headers, $alignments, $rows ) );

	return implode( "\n", $lines ) . "\n";
}

/**
 * @return ?array<string,mixed>
 */
function load_report( string $path ): ?array {
	if ( ! is_file( $path ) || 0 === filesize( $path ) ) {
		return null;
	}
	// phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Standalone CI helper reading local artifacts.
	$raw = file_get_contents( $path );
	if ( false === $raw ) {
		return null;
	}
	$decoded = json_decode( $raw, true );
	return is_array( $decoded ) ? $decoded : null;
}

function ui_metric_value( mixed $value ): string {
	if ( ! is_numeric( $value ) ) {
		return 'n/a';
	}
	return (string) (int) round( (float) $value );
}

/**
 * Builds an aligned GitHub-flavored markdown table.
 *
 * @param array<int,string>            $headers    Column headers.
 * @param array<int,string>            $alignments `left` or `right` per column.
 * @param array<int,array<int,string>> $rows       Pre-stringified cell values.
 * @return array<int,string>
 */
function markdown_table( array $headers, array $alignments, array $rows ): array {
	$widths = array_map( 'strlen', $headers );
	foreach ( $rows as $row ) {
		foreach ( $row as $index => $cell ) {
			$widths[ $index ] = max( $widths[ $index ] ?? 0, strlen( $cell ) );
		}
	}
	foreach ( $widths as $index => $width ) {
		$widths[ $index ] = max( 3, $width );
	}

	$format_row = static function ( array $row ) use ( $alignments, $widths ): string {
		foreach ( $row as $index => $cell ) {
			$pad_type      = 'right' === ( $alignments[ $index ] ?? 'left' ) ? STR_PAD_LEFT : STR_PAD_RIGHT;
			$row[ $index ] = str_pad( $cell, $widths[ $index ], ' ', $pad_type );
		}
		return '| ' . implode( ' | ', $row ) . ' |';
	};

	$separator = array();
	foreach ( $widths as $index => $width ) {
		$separator[] = 'right' === ( $alignments[ $index ] ?? 'left' )
			? str_repeat( '-', $width - 1 ) . ':'
			: str_repeat( '-', $width );
	}

	return array_merge(
		array( $format_row( $headers ), '| ' . implode( ' | ', $separator ) . ' |' ),
		array_map( $format_row, $rows )
	);
}
