allowBuilds:
    '@parcel/watcher': true
    core-js: true
    core-js-pure: true
    fs-ext-extra-prebuilt: true
    unrs-resolver: true
overrides:
    '@babel/plugin-transform-modules-systemjs': 7.29.7
    '@babel/runtime': 7.29.7
    '@tanstack/history': 1.161.6
    '@tanstack/react-router': 1.168.23
    '@tanstack/router-core': 1.168.15
    '@wordpress/a11y': 4.46.0
    '@wordpress/admin-ui': 2.1.0
    '@wordpress/api-fetch': 7.46.0
    '@wordpress/base-styles': 8.0.0
    '@wordpress/block-editor': 15.19.0
    '@wordpress/blocks': 15.19.0
    '@wordpress/commands': 1.46.0
    '@wordpress/components': 33.1.0
    '@wordpress/compose': 7.46.0
    '@wordpress/core-data': 7.46.0
    '@wordpress/data': 10.46.0
    '@wordpress/dataviews': 14.3.0
    '@wordpress/date': 5.46.0
    '@wordpress/element': 6.46.0
    '@wordpress/eslint-plugin': 25.2.0
    '@wordpress/fields': 0.38.0
    '@wordpress/global-styles-engine': 1.13.0
    '@wordpress/global-styles-ui': 1.13.0
    '@wordpress/html-entities': 4.46.0
    '@wordpress/i18n': 6.19.0
    '@wordpress/icons': 13.1.0
    '@wordpress/image-cropper': 1.10.0
    '@wordpress/interface': 9.31.0
    '@wordpress/keyboard-shortcuts': 5.46.0
    '@wordpress/keycodes': 4.46.0
    '@wordpress/media-editor': 0.9.0
    '@wordpress/media-fields': 0.11.0
    '@wordpress/media-utils': 5.46.0
    '@wordpress/notices': 5.46.0
    '@wordpress/patterns': 2.46.0
    '@wordpress/plugins': 7.46.0
    '@wordpress/preferences': 4.46.0
    '@wordpress/primitives': 4.46.0
    '@wordpress/private-apis': 1.46.0
    '@wordpress/reusable-blocks': 5.46.0
    '@wordpress/rich-text': 7.46.0
    '@wordpress/route': 0.12.0
    '@wordpress/router': 1.46.0
    '@wordpress/server-side-render': 6.22.0
    '@wordpress/stylelint-config': 23.38.0
    '@wordpress/style-runtime': 0.2.0
    '@wordpress/theme': 0.13.0
    '@wordpress/ui': 0.13.0
    '@wordpress/upload-media': 0.31.0
    '@wordpress/url': 4.46.0
    '@wordpress/viewport': 6.46.0
    '@wordpress/views': 1.13.0
    ajv: 8.18.0
    axios: 1.16.0
    basic-ftp: 5.3.1
    fast-xml-builder: 1.2.0
    ip-address: 10.1.1
    'markdownlint-cli@0.31.1>minimatch': 3.1.5
    qs: 6.15.2
    serialize-javascript: 7.0.5
    tmp: 0.2.7
