name: Build

on:
    push:
        branches: [main]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7.0.0

            - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
              with:
                  version: 11.0.8
                  standalone: true

            - uses: actions/setup-node@v6
              with:
                  node-version: '24.15'
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile
            - run: pnpm run build
